### ISSUE TITLE
Help needed on deploying this example for tomcat WITHOUT using PROFILES

### ISSUE THREAD

**Issue by dzoneuser** [openzipkin/brave-example#24]
I tried the example using Brave-zipkin[https://github.com/openzipkin/brave-webmvc-example/tree/master/webmvc3]. Everything looks fine for me.. except that, in the given example jetty server deploys the application twice, one for FrontEnd and another for Backend(using two profiles). Whereas I need to use tomcat-server without using any profiles.

Can anyone help me how to use this same tool for deploying in Tomcat-server and start the application without using profiles? kindly help

**Comment by adriancole** [comment]
you can use the war file created by the build process https://github.com/openzipkin/brave-webmvc-example/blob/master/webmvc3/pom.xml#L101 let me know if you want more details

**Comment by adriancole** [comment]
in the docker directory you can see scripts that use the war file created by mvn package. These produce working examples, though we use jetty not tomcat. https://hub.docker.com/repository/docker/openzipkin/example-brave
